// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32km7LRDGvqQn0kechPXvxqex8eSWlfk',
    appId: '1:1005636433625:web:51d447136488efdb2ab0c8',
    messagingSenderId: '1005636433625',
    projectId: 'library-management-cb0b6',
    authDomain: 'library-management-cb0b6.firebaseapp.com',
    storageBucket: 'library-management-cb0b6.firebasestorage.app',
    measurementId: 'G-E5PD97TM6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrhw59wJ9yD15L3BStndPHY8BO0ZumkW4',
    appId: '1:1005636433625:android:f80f37863089339a2ab0c8',
    messagingSenderId: '1005636433625',
    projectId: 'library-management-cb0b6',
    storageBucket: 'library-management-cb0b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWQOubM9PtfIas36ed4pg0xzUHuaCm_E',
    appId: '1:1005636433625:ios:250a222e49e0c01b2ab0c8',
    messagingSenderId: '1005636433625',
    projectId: 'library-management-cb0b6',
    storageBucket: 'library-management-cb0b6.firebasestorage.app',
    iosClientId: '1005636433625-ori253giibmd9ofiq4lbfnksn5ekpaot.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPWQOubM9PtfIas36ed4pg0xzUHuaCm_E',
    appId: '1:1005636433625:ios:250a222e49e0c01b2ab0c8',
    messagingSenderId: '1005636433625',
    projectId: 'library-management-cb0b6',
    storageBucket: 'library-management-cb0b6.firebasestorage.app',
    iosClientId: '1005636433625-ori253giibmd9ofiq4lbfnksn5ekpaot.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD32km7LRDGvqQn0kechPXvxqex8eSWlfk',
    appId: '1:1005636433625:web:841ad43208c945592ab0c8',
    messagingSenderId: '1005636433625',
    projectId: 'library-management-cb0b6',
    authDomain: 'library-management-cb0b6.firebaseapp.com',
    storageBucket: 'library-management-cb0b6.firebasestorage.app',
    measurementId: 'G-3FK4L8HD4P',
  );
}
